spring.application.name=guia-productor

server.port=${SERVER_PORT:8080}

spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}

spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:guias}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guias123}

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always